version: "3"

services:
  wireguard:
      image: lscr.io/linuxserver/wireguard:latest
      container_name: wireguard
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Nicosia
        - PEERS=peeruser1
        - PEERDNS=auto
        - ALLOWEDIPS=0.0.0.0/0
      volumes:
        - /opt/wireguard/config:/config
      ports:
        - 51820:51820/udp
      dns:
        - 172.21.0.7
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
      restart: unless-stopped
      networks:
        containers:
          ipv4_address: 172.21.0.5
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Asia/Nicosia'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './resolv.conf:/etc/resolv.conf'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.21.0.7
networks:
  containers:
      ipam:
        config:
          - subnet: 172.21.0.0/24