version: '2'
services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
      - USER=admin
      - PASS=adminadmin
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - tx-config:/config
      - tx-downloads:/downloads
      - tx-watch:/watch
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - tx-downloads:/downloads
    restart: "unless-stopped"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
    volumes:
      - sonarr-config:/config
      - tx-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
    volumes:
      - bazarr-config:/config
      - tx-downloads:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.7.7
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
    volumes:
      - jellyfin-config:/config
      - tx-downloads:/data
  # devices:
   #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 8920:8920
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Nicosia
      - NZBGET_USER=admin
      - NZBGET_PASS=admin
    volumes:
      - nzbget-config:/config
      - tx-downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

volumes:
  tx-config:
  tx-downloads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/jfu/NESO HDD/raspberry #mount path
  tx-watch:
  radarr-config:
  sonarr-config:
  bazarr-config:
  jackett-config:
  jackett-blackhole:
  jellyfin-config:
  nzbget-config:

networks:
  mynetwork:
    external: true
